### ISSUE TITLE
unticking use TLS 1.2 doesn't update the connect url properly.

### ISSUE THREAD

**Issue by re9177** [yellows111/collab-vm-csharp-client#3]
expected behavior: replaces :443 with :80

actual result: connect url doesn't change, clicking connect causes an error.

OS: Win7 SP1 x64

**Comment by Undefishin** [comment]
Good Job

**Comment by re9177** [comment]
> Good Job

Goodest Jobs In YellowCode Programming Sessions, Provide Best softwares and Boohbah.
